In [16]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

### 파일 전처리
### 하나의 열에 name, type 값이 같이 들어있어서 나눠주고, 새로운 csv 파일로 저장

In [53]:
# 원본 파일 열어보면 맨 위에 나온 숫자 = 행의 갯수
# 직접 지워서 사용함


# 1. list_attr_cloth 파일 

df_1 = pd.read_csv('E:\Project\list_attr_cloth.txt')
display(df_1)

df_1.columns #['attribute_name  attribute_type']
df_1['attribute_name'] = df_1['attribute_name  attribute_type'].str[:-1]
df_1['attribute_type'] = df_1['attribute_name  attribute_type'].str[-1]
display(df_1)
df_1.to_csv('E:\Project\list_attr_cloth.csv', header=True, index=False)


# 2. list_attr_img


# 3. list_category_cloth


# 4. list_category_img

df_2 = pd.read_csv('E:\Project\list_category_img.txt', encoding='UTF-8')
display(df_2)

     attribute_name  attribute_type
0    a-line                       3
1    abstract                     1
2    abstract chevron             1
3    abstract chevron print       1
4    abstract diamond             1
..                              ...
995  zip-pocket                   4
996  zip-up                       4
997  zipped                       4
998  zipper                       4
999  zippered                     4

[1000 rows x 1 columns]

,attribute_name attribute_type,attribute_name,attribute_type
0,a-line 3,a-line,3
1,abstract 1,abstract,1
2,abstract chevron 1,abstract chevron,1
3,abstract chevron print 1,abstract chevron print,1
4,abstract diamond 1,abstract diamond,1
...,...,...,...
995,zip-pocket 4,zip-pocket,4
996,zip-up 4,zip-up,4
997,zipped 4,zipped,4
998,zipper 4,zipper,4
999,zippered 4,zippered,4

ParserError: Error tokenizing data. C error: Expected 1 fields in line 47206, saw 2