In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('./matrix_codibook_1000.csv')

In [7]:
ca_df = df[df['style']=='Casual']

In [8]:
ca_df.head()

,img_dir,style,top shape,top pattern,bottom shape,bottom pattern,one-piece,one-piece pattern
0,codibook (3).jpg,Casual,NaN,NaN,Cotten-long-pants,None,NaN,NaN
4,codibook (4).jpg,Casual,Shirts,Graphic,H-line-skirt,None,NaN,NaN
6,codibook (7).jpg,Casual,NaN,NaN,Cotten-long-pants,None,NaN,NaN
7,codibook (12).jpg,Casual,NaN,NaN,H-line-skirt,None,NaN,NaN
12,codibook (13).jpg,Casual,Shirts,None,Chiffon-skirt,Stripe,NaN,NaN

In [10]:
ca_df_2 = ca_df[['top shape','top pattern', 'bottom shape', 'bottom pattern']]

In [13]:
ca_df_3 = ca_df_2.dropna(axis = 0)

In [22]:
ca_df_3.head()

           top shape top pattern   bottom shape bottom pattern
4             Shirts     Graphic   H-line-skirt           None
12            Shirts        None  Chiffon-skirt         Stripe
14   Long-sleeve-tee        None  Chiffon-skirt           None
17   Long-sleeve-tee      Stripe        Cutoffs           None
19  Short-sleeve-tee      Stripe   H-line-skirt            Dot

In [24]:
ca_df_3['zeros'] = 1

C:\Users\student\Anaconda3\envs\cpu_env\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [32]:
f_df=ca_df_3.pivot_table('zeros',index=['top shape','top pattern'],columns=['bottom shape', 'bottom pattern'], aggfunc='count')

In [33]:
f_df

bottom shape                 Chiffon-skirt                                  \
bottom pattern                       Check  Dot Floral Leopard None Stripe
top shape        top pattern
Hoodie           Check                 NaN  NaN    NaN     NaN  NaN    NaN
                 Graphic               NaN  NaN    NaN     NaN  NaN    NaN
                 None                  2.0  NaN    NaN     NaN  2.0    1.0
                 Stripe                NaN  NaN    NaN     NaN  NaN    NaN
Long-sleeve-tee  Check                 NaN  NaN    NaN     NaN  NaN    NaN
                 Graphic               1.0  NaN    NaN     NaN  1.0    NaN
                 None                  2.0  1.0    1.0     1.0  3.0    NaN
                 Stripe                NaN  NaN    NaN     NaN  NaN    1.0
Shirts           Check                 NaN  NaN    NaN     NaN  NaN    NaN
                 Floral                NaN  NaN    NaN     NaN  NaN    NaN
                 Graphic               NaN  NaN    NaN     NaN  NaN    NaN
                 None                  4.0  NaN    3.0     NaN  2.0    1.0
                 Stripe                NaN  NaN    NaN     NaN  1.0    NaN
Short-sleeve-tee Graphic               NaN  2.0    NaN     1.0  NaN    1.0
                 None                  NaN  NaN    NaN     1.0  NaN    NaN
                 Stripe                NaN  1.0    NaN     NaN  NaN    NaN

bottom shape                 Cotten-long-pants               Cutoffs  ...  \
bottom pattern                             Dot Graphic  None   Check  ...
top shape        top pattern                                          ...
Hoodie           Check                     NaN     NaN   1.0     NaN  ...
                 Graphic                   NaN     NaN   1.0     NaN  ...
                 None                      1.0     NaN   6.0     NaN  ...
                 Stripe                    NaN     NaN   1.0     NaN  ...
Long-sleeve-tee  Check                     NaN     NaN   NaN     NaN  ...
                 Graphic                   NaN     NaN   7.0     1.0  ...
                 None                      NaN     1.0  36.0     2.0  ...
                 Stripe                    NaN     NaN   4.0     NaN  ...
Shirts           Check                     NaN     NaN   1.0     NaN  ...
                 Floral                    1.0     NaN   1.0     NaN  ...
                 Graphic                   NaN     NaN   1.0     NaN  ...
                 None                      NaN     NaN  29.0     1.0  ...
                 Stripe                    NaN     NaN   6.0     NaN  ...
Short-sleeve-tee Graphic                   NaN     NaN   3.0     NaN  ...
                 None                      NaN     NaN   4.0     NaN  ...
                 Stripe                    NaN     NaN   4.0     1.0  ...

bottom shape                               H-line-skirt                     \
bottom pattern               Leopard  None        Check  Dot Graphic  None
top shape        top pattern
Hoodie           Check           1.0   1.0          NaN  NaN     NaN   NaN
                 Graphic         NaN   5.0          2.0  NaN     NaN   NaN
                 None            NaN   2.0          NaN  NaN     NaN   3.0
                 Stripe          NaN   NaN          NaN  NaN     NaN   NaN
Long-sleeve-tee  Check           NaN   NaN          NaN  1.0     NaN   NaN
                 Graphic         NaN   1.0          NaN  NaN     NaN   8.0
                 None            1.0  12.0          6.0  1.0     NaN  10.0
                 Stripe          NaN   3.0          NaN  NaN     NaN   3.0
Shirts           Check           NaN   1.0          NaN  NaN     NaN   2.0
                 Floral          1.0   1.0          NaN  NaN     NaN   NaN
                 Graphic         NaN   NaN          NaN  NaN     NaN   1.0
                 None            1.0  14.0          3.0  NaN     1.0   9.0
                 Stripe          NaN   1.0          1.0  NaN     NaN   1.0
Short-sleeve-tee Graphic         NaN   3.0          NaN  NaN     NaN   2.0
                 None            NaN   2.0          1.0  NaN     NaN   5.0
                 Stripe          NaN   3.0          NaN  1.0     1.0   3.0

bottom shape                        Jeans
bottom pattern               Stripe Check Leopard  None
top shape        top pattern
Hoodie           Check          NaN   NaN     NaN   NaN
                 Graphic        NaN   NaN     NaN   NaN
                 None           NaN   NaN     NaN   NaN
                 Stripe         NaN   NaN     NaN   NaN
Long-sleeve-tee  Check          NaN   NaN     NaN   NaN
                 Graphic        NaN   NaN     NaN   4.0
                 None           2.0   1.0     2.0   6.0
                 Stripe         NaN   NaN     NaN   1.0
Shirts           Check          NaN   NaN     NaN   NaN
                 Floral         NaN   NaN     NaN   NaN
                 Graphic        NaN   NaN     NaN   1.0
                 None           NaN   NaN     NaN  10.0
                 Stripe         NaN   NaN     NaN   3.0
Short-sleeve-tee Graphic        NaN   NaN     NaN   NaN
                 None           NaN   NaN     NaN   6.0
                 Stripe         NaN   NaN     NaN   1.0

[16 rows x 23 columns]

In [40]:
f_df2 = f_df.fillna(0)

In [65]:
# 하의에 대한 상의 값 찾기
matched_upper = f_df2.xs(('Chiffon-skirt','None'), axis=1).sort_values(ascending=False).index[0]

matched_upper_shape = matched_upper[0]
matched_upper_pattern = matched_upper[1]

In [66]:
# 상의에 대한 하의 값 찾기
matched_lower = f_df2.loc[('Short-sleeve-tee','None')].sort_values(ascending=False).index[0]

matched_lower_shape = matched_upper[0]
matched_lower_pattern = matched_upper[1]