In [1]:
import cv2
import os
import matplotlib.pyplot as plt
# import requests
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import matplotlib.patches as patches
from matplotlib.pyplot import imshow
import numpy as np
from PIL import Image

In [3]:
# 폴더 생성 함수
def createfolder(foler_dir):
    try:
        if not os.path.exists(folder_dir):
            os.makedirs(folder_dir)
    except OSError:
        print('Error Creating directory'+folder_dir)

In [4]:
# noface_img 하위 폴더 만들기
path = './data/img'
file_list = os.listdir(path)

for folder_name in file_list:
    path = './data/cut_img/'
    folder_dir = path + folder_name
    createfolder(folder_dir)

In [8]:
import pandas as pd
data = pd.read_csv('./data/원본 데이터/list_bbox.csv')
data

                                               image_name  x1  y1   x2   y2
0         img/Sheer_Pleated-Front_Blouse/img_00000001.jpg  72  79  232  273
1         img/Sheer_Pleated-Front_Blouse/img_00000002.jpg  67  59  155  161
2         img/Sheer_Pleated-Front_Blouse/img_00000003.jpg  65  65  156  200
3         img/Sheer_Pleated-Front_Blouse/img_00000004.jpg  51  62  167  182
4         img/Sheer_Pleated-Front_Blouse/img_00000005.jpg  46  88  166  262
...                                                   ...  ..  ..  ...  ...
289217  img/Paisley_Print_Babydoll_Dress/img_00000050.jpg   1   1  300  300
289218  img/Paisley_Print_Babydoll_Dress/img_00000051.jpg  14  58  225  277
289219  img/Paisley_Print_Babydoll_Dress/img_00000052.jpg  18  41  149  230
289220  img/Paisley_Print_Babydoll_Dress/img_00000053.jpg  75  47  220  300
289221  img/Paisley_Print_Babydoll_Dress/img_00000054.jpg  36  63  202  296

[289222 rows x 5 columns]

In [11]:
for _ in range(0,289222):
    try:
        jpg_file = './data/img/' + data['image_name'][_].split("/")[1] + "/" + data['image_name'][_].split("/")[2]
        img = Image.open(jpg_file,'r')
        dim = (int(data['x1'][_])
               ,int(data['y1'][_])
               ,int(data['x2'][_])
               ,int(data['y2'][_]))
        
        crop_img = img.crop(dim)
        name = './data/cut_img/' + data['image_name'][_].split("/")[1] + "/" + data['image_name'][_].split("/")[2]
        crop_img.save(name)
        if _ % 1000 ==0:
            print(_)
    except:
        print(_)
        print(name)

59411
./data/cut_img/Young,_Beautiful,_&_Glamorous_Sweater/img_00000043.jpg